# UI translations for each language
LANGUAGE_UI_STRINGS = {
    "ca": {
        "heard": "He sentit",
        "great": "Molt bé!",
        "try_again": "Torna-ho a intentar",
        "keep_trying": "Continua intentant-ho...",
    },
    "cs": {
        "heard": "Slyšel jsem",
        "great": "Skvělé!",
        "try_again": "Zkuste to znovu",
        "keep_trying": "Pokračujte...",
    },
    "de": {
        "heard": "Gehört",
        "great": "Großartig!",
        "try_again": "Versuchen Sie es erneut",
        "keep_trying": "Weiter versuchen...",
    },
    "en": {
        "heard": "Heard",
        "great": "Great!",
        "try_again": "Try again",
        "keep_trying": "Keep trying...",
    },
    "eo": {
        "heard": "Aŭdis",
        "great": "Bonege!",
        "try_again": "Provu denove",
        "keep_trying": "Daŭrigu provi...",
    },
    "es": {
        "heard": "Oí",
        "great": "¡Genial!",
        "try_again": "Inténtalo de nuevo",
        "keep_trying": "Sigue intentándolo...",
    },
    "fa": {
        "heard": "شنیدم",
        "great": "عالی!",
        "try_again": "دوباره امتحان کنید",
        "keep_trying": "به تلاش ادامه دهید...",
    },
    "fr": {
        "heard": "J'ai entendu",
        "great": "Excellent!",
        "try_again": "Réessayez",
        "keep_trying": "Continuez à essayer...",
    },
    "gu": {
        "heard": "સાંભળ્યું",
        "great": "સરસ!",
        "try_again": "ફરીથી પ્રયત્ન કરો",
        "keep_trying": "પ્રયાસ કરતા રહો...",
    },
    "hi": {
        "heard": "सुना",
        "great": "बढ़िया!",
        "try_again": "फिर से कोशिश करें",
        "keep_trying": "कोशिश जारी रखें...",
    },
    "it": {
        "heard": "Sentito",
        "great": "Ottimo!",
        "try_again": "Riprova",
        "keep_trying": "Continua a provare...",
    },
    "ja": {
        "heard": "聞こえた",
        "great": "素晴らしい!",
        "try_again": "もう一度",
        "keep_trying": "続けて...",
    },
    "kk": {
        "heard": "Естідім",
        "great": "Тамаша!",
        "try_again": "Қайта көріңіз",
        "keep_trying": "Әрекет жалғастырыңыз...",
    },
    "ko": {
        "heard": "들었음",
        "great": "훌륭해요!",
        "try_again": "다시 시도하세요",
        "keep_trying": "계속 시도하세요...",
    },
    "ky": {
        "heard": "Уктум",
        "great": "Мыкты!",
        "try_again": "Кайра аракет кылыңыз",
        "keep_trying": "Аракет кыла бериңиз...",
    },
    "nl": {
        "heard": "Ik hoorde",
        "great": "Geweldig!",
        "try_again": "Probeer opnieuw",
        "keep_trying": "Blijf proberen...",
    },
    "pl": {
        "heard": "Słyszałem",
        "great": "Świetnie!",
        "try_again": "Spróbuj ponownie",
        "keep_trying": "Próbuj dalej...",
    },
    "pt": {
        "heard": "Ouvi",
        "great": "Ótimo!",
        "try_again": "Tente novamente",
        "keep_trying": "Continue tentando...",
    },
    "ru": {
        "heard": "Слышал",
        "great": "Отлично!",
        "try_again": "Попробуйте снова",
        "keep_trying": "Продолжайте пытаться...",
    },
    "te": {
        "heard": "విన్నాను",
        "great": "గొప్ప!",
        "try_again": "మళ్లీ ప్రయత్నించండి",
        "keep_trying": "ప్రయత్నం కొనసాగించండి...",
    },
    "tg": {
        "heard": "Шунидам",
        "great": "Хуб!",
        "try_again": "Боз кӯшиш кунед",
        "keep_trying": "Кӯшиш кунед...",
    },
    "tr": {
        "heard": "Duydum",
        "great": "Harika!",
        "try_again": "Tekrar deneyin",
        "keep_trying": "Denemeye devam edin...",
    },
    "uk": {
        "heard": "Почув",
        "great": "Чудово!",
        "try_again": "Спробуйте знову",
        "keep_trying": "Продовжуйте...",
    },
    "uz": {
        "heard": "Eshitdim",
        "great": "Ajoyib!",
        "try_again": "Qayta urinib ko'ring",
        "keep_trying": "Urinishda davom eting...",
    },
    "vi": {
        "heard": "Đã nghe",
        "great": "Tuyệt vời!",
        "try_again": "Thử lại",
        "keep_trying": "Tiếp tục thử...",
    },
    "zh": {
        "heard": "听到",
        "great": "太棒了!",
        "try_again": "再试一次",
        "keep_trying": "继续尝试...",
    },
}
